/**
 * Rizz Power-Up Meme Images
 * 
 * This file provides access to the meme images used in the Rizz Power-Up app.
 * Images are categorized as "good" (positive rizz) or "bad" (negative rizz).
 * 
 * THIS FILE IS AUTO-GENERATED BY THE MEME-CONVERTER TOOL.
 * DO NOT EDIT DIRECTLY - CHANGES WILL BE OVERWRITTEN.
 */

/**
 * Interface for meme image data
 */
export interface MemeImage {
  /** Unique identifier for the image */
  id: string;
  /** Descriptive name of the image */
  name: string;
  /** Path to the image file */
  path: string;
  /** Description of the image based on the prompt */
  description: string;
  /** Original prompt title from the rizz_image_prompts_no_text_overlay.md file */
  promptTitle?: string;
  /** Original prompt ID from the rizz_image_prompts_no_text_overlay.md file */
  promptId?: number;
  /** Rizz Level stat (-10 to +10) */
  rizzLevel: number;
  /** Vibe Level stat (-10 to +10) */
  vibeLevel: number;
  /** Swagger stat (-10 to +10) */
  swagger: number;
  /** Cringe Avoidance stat (-10 to +10) */
  cringeAvoidance: number;
}

/**
 * Good (positive rizz) meme images
 */
export const goodImages: MemeImage[] = [
  {
    "id": "primal-power-unleashed-1",
    "name": "Primal Power Unleashed",
    "path": "/memes/good/primal-power-unleashed-01jtfbzvwjf0frbzz2fgx0ehr5.png",
    "description": "A character mid-transformation into a glowing, animalistic form surrounded by lightning, shattered chains, and streaming hair. Think anime-style power surge.",
    "promptTitle": "Unleashed primal rizz beast mode.",
    "promptId": 10,
    "rizzLevel": 7,
    "vibeLevel": 4,
    "swagger": 9,
    "cringeAvoidance": 8
  },
  {
    "id": "primal-power-unleashed-2",
    "name": "Primal Power Unleashed",
    "path": "/memes/good/primal-power-unleashed-01jtfbzvwhfs6scng73tg4qkwg.png",
    "description": "A character mid-transformation into a glowing, animalistic form surrounded by lightning, shattered chains, and streaming hair. Think anime-style power surge.",
    "promptTitle": "Unleashed primal rizz beast mode.",
    "promptId": 10,
    "rizzLevel": 7,
    "vibeLevel": 6,
    "swagger": 2,
    "cringeAvoidance": 2
  },
  {
    "id": "meditative-cat-serenity-1",
    "name": "Meditative Cat Serenity",
    "path": "/memes/good/meditative-cat-serenity-01jtfbyb6bejg9zh72d5aqsv6n.png",
    "description": "A negative rizz image showing meditative cat serenity.",
    "promptTitle": "meditative cat serenity",
    "promptId": 0,
    "rizzLevel": 9,
    "vibeLevel": 3,
    "swagger": 9,
    "cringeAvoidance": 9
  },
  {
    "id": "meditative-cat-serenity-2",
    "name": "Meditative Cat Serenity",
    "path": "/memes/good/meditative-cat-serenity-01jtfbyb6afw8vsn1whywp6kgv.png",
    "description": "A negative rizz image showing meditative cat serenity.",
    "promptTitle": "meditative cat serenity",
    "promptId": 0,
    "rizzLevel": 6,
    "vibeLevel": 4,
    "swagger": 3,
    "cringeAvoidance": 9
  },
  {
    "id": "maximal-clout-strut-1",
    "name": "Maximal Clout Strut",
    "path": "/memes/good/maximal-clout-strut-01jtfbjr3bfyx9as87wbyb3mgq.png",
    "description": "A character struts down the street with clout goggles and designer drip, surrounded by floating likes, paparazzi drones, and lens flares. Think meme fame energy.",
    "promptTitle": "Exuding max clout per nanosecond.",
    "promptId": 2,
    "rizzLevel": 4,
    "vibeLevel": 7,
    "swagger": 10,
    "cringeAvoidance": 9
  },
  {
    "id": "maximal-clout-strut-2",
    "name": "Maximal Clout Strut",
    "path": "/memes/good/maximal-clout-strut-01jtfbjr3af2ebg7s6esg7mz8q.png",
    "description": "A character struts down the street with clout goggles and designer drip, surrounded by floating likes, paparazzi drones, and lens flares. Think meme fame energy.",
    "promptTitle": "Exuding max clout per nanosecond.",
    "promptId": 2,
    "rizzLevel": 8,
    "vibeLevel": 2,
    "swagger": 2,
    "cringeAvoidance": 3
  },
  {
    "id": "hallway-heroics-1",
    "name": "Hallway Heroics",
    "path": "/memes/good/hallway-heroics-01jtfbjde3eavsyk1jxwtc7a08.png",
    "description": "A person walking in slow motion down a school hallway with dramatic lighting, other students frozen mid-reaction in admiration, petals floating in the air, and glowing synthwave sun rays behind them. Vaporwave color palette.",
    "promptTitle": "Main character energy.",
    "promptId": 1,
    "rizzLevel": 7,
    "vibeLevel": 6,
    "swagger": 2,
    "cringeAvoidance": 2
  },
  {
    "id": "hallway-heroics-2",
    "name": "Hallway Heroics",
    "path": "/memes/good/hallway-heroics-01jtfbjde2egv9gq8462g4bq50.png",
    "description": "A person walking in slow motion down a school hallway with dramatic lighting, other students frozen mid-reaction in admiration, petals floating in the air, and glowing synthwave sun rays behind them. Vaporwave color palette.",
    "promptTitle": "Main character energy.",
    "promptId": 1,
    "rizzLevel": 2,
    "vibeLevel": 6,
    "swagger": 6,
    "cringeAvoidance": 9
  },
  {
    "id": "boho-vibe-overload-1",
    "name": "Boho Vibe Overload",
    "path": "/memes/good/boho-vibe-overload-01jtfbvygffm8ajr1786n9yrcg.png",
    "description": "A serene monk levitating over a koi pond inside a tranquil temple surrounded by emoji-shaped lotus flowers. Mist and cosmic vibes in the background.",
    "promptTitle": "Rizz Zen achieved.",
    "promptId": 9,
    "rizzLevel": 7,
    "vibeLevel": 6,
    "swagger": 7,
    "cringeAvoidance": 8
  },
  {
    "id": "boho-vibe-overload-2",
    "name": "Boho Vibe Overload",
    "path": "/memes/good/boho-vibe-overload-01jtfbvygefqza65784jdaazk7.png",
    "description": "A serene monk levitating over a koi pond inside a tranquil temple surrounded by emoji-shaped lotus flowers. Mist and cosmic vibes in the background.",
    "promptTitle": "Rizz Zen achieved.",
    "promptId": 9,
    "rizzLevel": 7,
    "vibeLevel": 3,
    "swagger": 9,
    "cringeAvoidance": 9
  }
];

/**
 * Bad (negative rizz) meme images
 */
export const badImages: MemeImage[] = [
  {
    "id": "rained-romance-ruin-1",
    "name": "Rained Romance Ruin",
    "path": "/memes/bad/rained-romance-ruin-01jtfbnr7eft9rp06awtc5y39j.png",
    "description": "A soaked character stands in the rain next to a destroyed smartphone and ghosted Tinder profile. A single umbrella flips inside-out.",
    "promptTitle": "Your rizz has been obliterated.",
    "promptId": 11,
    "rizzLevel": -10,
    "vibeLevel": -2,
    "swagger": -7,
    "cringeAvoidance": -7
  },
  {
    "id": "rained-romance-ruin-2",
    "name": "Rained Romance Ruin",
    "path": "/memes/bad/rained-romance-ruin-01jtfbnr7dfdc8qs3shvk3ppsw.png",
    "description": "A soaked character stands in the rain next to a destroyed smartphone and ghosted Tinder profile. A single umbrella flips inside-out.",
    "promptTitle": "Your rizz has been obliterated.",
    "promptId": 11,
    "rizzLevel": -10,
    "vibeLevel": -2,
    "swagger": -6,
    "cringeAvoidance": -6
  },
  {
    "id": "lonely-raw-hot-dog-1",
    "name": "Lonely Raw Hot Dog",
    "path": "/memes/bad/lonely-raw-hot-dog-01jtfbv8cdeb7vd8ks2y50xhmf.png",
    "description": "A sad hot dog in human form sits alone on a picnic bench, raw and slightly dripping, while others laugh around a bonfire in the distance.",
    "promptTitle": "Rizzless, like an uncooked glizzy.",
    "promptId": 13,
    "rizzLevel": -7,
    "vibeLevel": -2,
    "swagger": -10,
    "cringeAvoidance": -1
  },
  {
    "id": "lonely-raw-hot-dog-2",
    "name": "Lonely Raw Hot Dog",
    "path": "/memes/bad/lonely-raw-hot-dog-01jtfbv8ccekgb4jzds965rwwz.png",
    "description": "A sad hot dog in human form sits alone on a picnic bench, raw and slightly dripping, while others laugh around a bonfire in the distance.",
    "promptTitle": "Rizzless, like an uncooked glizzy.",
    "promptId": 13,
    "rizzLevel": -6,
    "vibeLevel": -4,
    "swagger": -7,
    "cringeAvoidance": -7
  },
  {
    "id": "empty-rizz-neon-car-1",
    "name": "Empty Rizz Neon Car",
    "path": "/memes/bad/empty-rizz-neon-car-01jtfc8c4keptv111e89d2b6cs.png",
    "description": "A person slumped over their phone beside a neon sports car with the gas cap open and a “low vibe” warning light blinking. Desert background, isolation.",
    "promptTitle": "Rizz tank empty.",
    "promptId": 18,
    "rizzLevel": -7,
    "vibeLevel": -5,
    "swagger": -5,
    "cringeAvoidance": -1
  },
  {
    "id": "empty-rizz-neon-car-2",
    "name": "Empty Rizz Neon Car",
    "path": "/memes/bad/empty-rizz-neon-car-01jtfc8c4jemp82rxe8p3jf80x.png",
    "description": "A person slumped over their phone beside a neon sports car with the gas cap open and a “low vibe” warning light blinking. Desert background, isolation.",
    "promptTitle": "Rizz tank empty.",
    "promptId": 18,
    "rizzLevel": -4,
    "vibeLevel": -5,
    "swagger": -2,
    "cringeAvoidance": -1
  },
  {
    "id": "cringe-meets-style-1",
    "name": "Cringe Meets Style",
    "path": "/memes/bad/cringe-meets-style-01jtfbpyhkfgabty7rpqc9dhkd.png",
    "description": "A cringeworthy character approaches a stylish group, who recoil in horror. Warning lights and emoji alarms blink behind them.",
    "promptTitle": "Main cringe energy detected.",
    "promptId": 12,
    "rizzLevel": -1,
    "vibeLevel": -5,
    "swagger": -9,
    "cringeAvoidance": -10
  },
  {
    "id": "cringe-meets-style-2",
    "name": "Cringe Meets Style",
    "path": "/memes/bad/cringe-meets-style-01jtfbpyhjfs6bm834s7q968mv.png",
    "description": "A cringeworthy character approaches a stylish group, who recoil in horror. Warning lights and emoji alarms blink behind them.",
    "promptTitle": "Main cringe energy detected.",
    "promptId": 12,
    "rizzLevel": -5,
    "vibeLevel": -7,
    "swagger": -4,
    "cringeAvoidance": -7
  },
  {
    "id": "chaotic-desktop-dilemma-1",
    "name": "Chaotic Desktop Dilemma",
    "path": "/memes/bad/chaotic-desktop-dilemma-01jtfc1jt6fy8ss491s42ct1j1.png",
    "description": "A chaotic desktop covered in flickering error popups and glowing smoothie spills. The user stares blankly as apps melt off-screen.",
    "promptTitle": "Overflow Rizzion – Exception Raised.",
    "promptId": 19,
    "rizzLevel": -9,
    "vibeLevel": -7,
    "swagger": -3,
    "cringeAvoidance": -1
  },
  {
    "id": "chaotic-desktop-dilemma-2",
    "name": "Chaotic Desktop Dilemma",
    "path": "/memes/bad/chaotic-desktop-dilemma-01jtfc1jt4e6pah9hn7zzcjpj9.png",
    "description": "A chaotic desktop covered in flickering error popups and glowing smoothie spills. The user stares blankly as apps melt off-screen.",
    "promptTitle": "Overflow Rizzion – Exception Raised.",
    "promptId": 19,
    "rizzLevel": -10,
    "vibeLevel": -10,
    "swagger": -4,
    "cringeAvoidance": -2
  }
];

/**
 * All meme images (both good and bad)
 */
export const allImages: MemeImage[] = [...goodImages, ...badImages];

/**
 * Get a random good (positive rizz) image
 * @returns A random good meme image
 */
export function getRandomGoodImage(): MemeImage {
  return goodImages[Math.floor(Math.random() * goodImages.length)];
}

/**
 * Get a random bad (negative rizz) image
 * @returns A random bad meme image
 */
export function getRandomBadImage(): MemeImage {
  return badImages[Math.floor(Math.random() * badImages.length)];
}

/**
 * Get a random image from all available memes
 * @returns A random meme image
 */
export function getRandomImage(): MemeImage {
  return allImages[Math.floor(Math.random() * allImages.length)];
}

/**
 * Get a random image based on the specified type
 * @param type 'good', 'bad', or 'any'
 * @returns A random meme image of the specified type
 */
export function getRandomImageByType(type: 'good' | 'bad' | 'any'): MemeImage {
  switch (type) {
    case 'good':
      return getRandomGoodImage();
    case 'bad':
      return getRandomBadImage();
    case 'any':
    default:
      return getRandomImage();
  }
}

/**
 * Get all images of a specific type
 * @param type 'good', 'bad', or 'all'
 * @returns Array of meme images of the specified type
 */
export function getImagesByType(type: 'good' | 'bad' | 'all'): MemeImage[] {
  switch (type) {
    case 'good':
      return goodImages;
    case 'bad':
      return badImages;
    case 'all':
    default:
      return allImages;
  }
}
